application: whatallo-hrd
version: 4
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: django
  version: "1.4"

handlers:
- url: /js
  static_dir: js

- url: /.*
  script: main.app
  secure: never
